collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3978495
  brandStrength: 1
  lightness: 0.2688172
  brandColors:
    - '#FFFFFF'
    - '#232426'
    - '#626367'
    - '#C6C7BF'
    - '#989BA2'
  rhythmicContrast: 0.327957
typography_spectrum: 0.5197133
layout_spectrum: 0.9032258
name: Remotes
