collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4462366
  brandStrength: 0.4569893
  lightness: 0.2437276
  brandColors:
    - '#FFFFFF'
    - '#363636'
    - '#94918F'
    - '#050505'
    - '#D4D4D4'
  rhythmicContrast: 0.7311828
typography_spectrum: 0.8978494
layout_spectrum: 0
name: Remotes
