collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.5197133
color:
  saturation: 0.7293907
  brandStrength: 0.4569893
  lightness: 0.4784946
  brandColors:
    - '#FFFFFF'
    - '#363636'
    - '#94918F'
    - '#050505'
    - '#D4D4D4'
  rhythmicContrast: 0.7150537
layout_spectrum: 0.4283154
name: Remotes
